### ISSUE TITLE
[feature] books section

### ISSUE THREAD

**Issue by deksden** [sindresorhus/awesome-electron#248]
https://leanpub.com/electron

**Comment by sindresorhus** [comment]
I dunno. It's a bit outdated. Last updated a year ago. There has been considerable changes to the Electron API since then. Not sure we're doing users any favors providing outdated knowledge. It's also riddled with typos. I think https://medium.com/developers-writing/building-a-desktop-application-with-electron-204203eeb658#.tkcxckxki is a much better intro to Electron.

**Comment by deksden** [comment]
Maybe! Did you know any other books on subject?

**Comment by sindresorhus** [comment]
Not really. We can add a Books section if someone proposes another book ;)
