### ISSUE TITLE
Who wants to be hired?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-electron#613]
This issue is for developers (individuals) looking for Electron-related work.

#### Developers

Share your information. Be succinct.

Please use this format:
- Location:
- Remote:
- Willing to relocate:
- Résumé/CV:
- Email:
- About me:

#### Companies

Please only email these addresses to discuss work opportunities regarding Electron development. No spam or recruiters!

---

Subscribe to this issue if you're looking to hire developers for Electron-related work.

**Comment by neggi** [comment]
Hello, we work intensively on electron contact me for more details.  
email: surajnegi@outlook.in
thanks

**Comment by linuxjuggler** [comment]
Hey My name is Zaher, and these are my information:

- **Location**: Currently living in Istanbul, Turkey
- **Remote**: Yes
- **Willing to relocate**: Yes
- **Résumé/CV**: https://zah.me/assets/uploads/static/CV.pdf
- **Email**: zaher[at]zah.me
- **About me**: I have been working as a backend developer using PHP for a long time, so most of my works are using anything related to PHP. My knowledge of JavaScript/NodeJS is not that bad, as I always try to improve myself. I can't say am new to **ElectronJS** but at the same time I can't say I've much work to show, except my latest work which is a monitoring application for your domains (more info can be found here https://electronjs.org/apps/domain-book and https://darawish.io/domainbook/), which I've built using Electron, Vue and currently I am adding PHP to the stack.

If there is anything else missing let me know, am more than happy to provide more information upon request.

Thanks

**Comment by Lax** [comment]
Hi, I'm Liu Lantao looking for a remote work or freelancer opportunities.

* Location: Shanghai, China
* Remote: Yes
* Willing to relocate: Yes
* Résumé/CV: https://about.liulantao.com/en/resume/compact/
* Email: liulantao(~at~)gmail.com
* About me: I worked as DevOps engineer since 2009. Before I quit my daily job and join a startup at 2017, I have worked on several companies include SNS website and SaaS service. I can code both frontend and backend, and I'm pretty interested in mobile and desktop software development.
Now I build things with Rails, VueJS, Electron, ReactNative, RubyMotion.
